### ISSUE TITLE
docker: Fix dependencies for 0.19 images

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-cloud#112]
- [x] The KPM plugin needs to be fixed to work against `0.19.x` branch (https://github.com/killbill/killbill-kpm-plugin/issues/2)
- [x] KPM latest version see https://github.com/killbill/killbill-cloud/issues/111
- [x] The kpm gem needs to be rebuilt (https://github.com/killbill/killbill-cloud/issues/114)

**Comment by pierre** [comment]
For the KPM plugin, see https://github.com/killbill/killbill-kpm-plugin/pull/1#issuecomment-356675814.

**Comment by pierre** [comment]
Note to self: after these fixes, our base images (both 18 and 19) will need to be rebuilt.

**Comment by pierre** [comment]
0.19 images rebuilt but see https://github.com/killbill/killbill-cloud/issues/111 for 0.18 images.
